### ISSUE TITLE
Languages covered

### ISSUE THREAD

**Issue by arafalov** [nicholasding/solr-lemmatizer#1]
Could the README be updated to mention which languages this covers and/or can cover?

I just featured the component in [the Solr Start newsletter](http://solr-start.com/), so a more clear documentation may help people to know when and how to use it.

**Comment by nicholasding** [comment]
@arafalov Thank you very much for supporting this project, I will work on it.

**Comment by sanketdangelpl** [comment]
How i can add custom words in custom text file for com.nicholasding.search.solr.LemmatizerFilterFactory
